preserve_hierarchy: true

language_mapping:
  two_letters_code:
    ru: ru    # гарантирует apps/.../ru.json (а не ru-RU.json)
    
files:
  - source: apps/i18n/core/en/LC_MESSAGES/django.po
    translation: apps/i18n/core/%two_letters_code%/LC_MESSAGES/django.po
    type: gettext
  - source: apps/i18n/chen/en.json
    translation: apps/i18n/chen/ru.json
    type: json
  - source: apps/i18n/koko/en.json
    translation: apps/i18n/koko/ru.json
    type: json
  - source: apps/i18n/lina/en.json
    translation: apps/i18n/lina/ru.json
    type: json
  - source: apps/i18n/luna/en.json
    translation: apps/i18n/luna/ru.json
    type: json
  - source: apps/i18n/lion/en.json
    translation: apps/i18n/lion/ru.json
    type: json
